# Generated by Django 6.0.1 on 2026-01-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('region', models.CharField(choices=[('heel', 'Heel'), ('arch', 'Arch'), ('toe', 'Toe')], max_length=10)),
                ('delta_temp', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('diagnosis', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FootRegionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('mean_temp', models.FloatField()),
                ('delta_temp', models.FloatField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainabilityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap_image', models.ImageField(upload_to='heatmaps/')),
                ('overlay_image', models.ImageField(upload_to='overlays/')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ThermographicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('delta_temp_left_right', models.FloatField()),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan')),
            ],
        ),
    ]
