# Generated by Django 6.0.1 on 2026-01-14 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
